# команда перезагрузки конфига /mobradiuslimiter (право: mobradiuslimiter.command)

# лимиты для отдельных типов мобов
limits:
  # лимит для визеров
  # список имен типов мобов: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
  WITHER:
    # максимальное количество мобов, которое может быть в указанном радиусе nearbyRadius
    limitNearby: 2
    # радиус, который определяет действие лимита limitNearby
    nearbyRadius: 800
    # максимальное количество мобов, которое может быть на весь мир
    limitWorld: 10
  SQUID:
    limitNearby: 10
    nearbyRadius: 800
    limitWorld: 40

# общий лимит для всех мобов
common-limit:
  # максимальное количество мобов, которое может быть в указанном радиусе nearbyRadius
  limitNearby: 400
  # радиус, который определяет действие лимита limitNearby
  nearbyRadius: 800

# типы мобов, которые плагин будет игнорить и не учитывать в общем лимите
ignore-entity-types:
  - ENDERMITE
  - ITEM_FRAME

world-limits: {}

# Типы мобов по важности.
# Сверху самые важные мобы.
# Важные мобы удаляются в последнюю очередь.
entity-type-priorities:
  - VILLAGER
  - ITEM_FRAME
  - ARMOR_STAND
  - RABBIT
  - DROPPED_ITEM
  - SHEEP
  - PAINTING
  - FALLING_BLOCK
  - EXPERIENCE_ORB
  - PIG
  - COW
  - SQUID
  - WITHER_SKULL
  - ZOMBIE_VILLAGER
  - IRON_GOLEM
  - THROWN_EXP_BOTTLE
  - ARROW
  - EGG
  - PIG_ZOMBIE
  - MUSHROOM_COW
  - MINECART_CHEST
  - MINECART_FURNACE
  - MINECART_TNT
  - MINECART_HOPPER
  - CHICKEN
  - WOLF
  - BOAT
  - OCELOT
  - HORSE
  - POLAR_BEAR
  - FIREBALL
  - SNOWBALL
  - ENDER_PEARL
  - ENDER_SIGNAL
  - SMALL_FIREBALL
  - SPLASH_POTION
  - LLAMA
  - MULE
  - DONKEY
  - PARROT
  - SKELETON
  - PRIMED_TNT
  - FIREWORK
  - HUSK
  - SPECTRAL_ARROW
  - SHULKER_BULLET
  - ENDER_CRYSTAL
  - LINGERING_POTION
  - FISHING_HOOK
  - SPIDER
  - GHAST
  - LIGHTNING
  - WEATHER
  - COMPLEX_PART
  - TIPPED_ARROW
  - SLIME
  - CREEPER
  - ZOMBIE
  - ENDERMAN
  - CAVE_SPIDER
  - SILVERFISH
  - SNOWMAN
  - ZOMBIE_VILLAGER
  - SKELETON_HORSE
  - ZOMBIE_HORSE
  - EVOKER_FANGS
  - EVOKER
  - VEX
  - VINDICATOR
  - ILLUSIONER
  - BLAZE
  - MAGMA_CUBE
  - ENDER_DRAGON
  - WITCH
  - WITHER
  - WITHER_SKELETON
  - MINECART_MOB_SPAWNER
  - AREA_EFFECT_CLOUD
  - MINECART_COMMAND
  - DRAGON_FIREBALL
  - LEASH_HITCH
  - STRAY
  - LLAMA_SPIT
  - GUARDIAN
  - ELDER_GUARDIAN
  - SHULKER
  - ENDERMITE
  - BAT
